import type { Metadata } from "next";

/**
 * Audience Types
 * 
 * Different user segments that see personalized messaging
 * and Open Graph images.
 */
export type Audience = "family" | "coparent" | "team" | "pta";

/**
 * OG Image Configuration
 * 
 * Generates audience-specific Open Graph metadata for social sharing.
 * Each audience gets customized imagery and messaging to improve
 * click-through rates from social media.
 * 
 * In production, these would be actual image URLs generated by:
 * - Next.js OG Image Generation API
 * - Cloudinary dynamic image transformations
 * - Pre-rendered static images in /public/og/
 */
interface OGImageConfig {
  title: string;
  description: string;
  image: string;
  imageAlt: string;
}

const OG_IMAGES: Record<Audience, OGImageConfig> = {
  family: {
    title: "KidSchedule – The Family Calendar That Actually Works",
    description:
      "School schedules, activities, and everyone's stuff — finally in one place. Syncs everywhere.",
    image: "/og/family.png",
    imageAlt: "Family using KidSchedule calendar app together",
  },
  coparent: {
    title: "KidSchedule – Co-Parenting Made Peaceful. Court-Ready When It's Not.",
    description:
      "Tamper-proof messaging. Documented everything. Built for your sanity — and your lawyer's.",
    image: "/og/coparent.png",
    imageAlt: "Co-parents managing custody schedule with KidSchedule",
  },
  team: {
    title: "KidSchedule – One Calendar for the Whole Team",
    description:
      "Parents subscribe and stay updated. Practices, games, and schedules synced automatically.",
    image: "/og/team.png",
    imageAlt: "Sports team parents viewing practice schedule on KidSchedule",
  },
  pta: {
    title: "KidSchedule – Run Your PTA Without the Chaos",
    description:
      "Member directory, events, volunteer signups, announcements. Everything in one place.",
    image: "/og/pta.png",
    imageAlt: "PTA organizers managing school events with KidSchedule",
  },
};

/**
 * Generate audience-specific Open Graph metadata
 * 
 * @param audience - The target audience segment
 * @returns Next.js Metadata object with OG tags
 * 
 * @example
 * export const metadata = generateOGMetadata("coparent");
 */
export function generateOGMetadata(audience: Audience): Metadata {
  const config = OG_IMAGES[audience];
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || "https://kidschedule.com";

  return {
    title: config.title,
    description: config.description,
    openGraph: {
      title: config.title,
      description: config.description,
      type: "website",
      url: baseUrl,
      siteName: "KidSchedule",
      images: [
        {
          url: `${baseUrl}${config.image}`,
          width: 1200,
          height: 630,
          alt: config.imageAlt,
          type: "image/png",
        },
      ],
      locale: "en_US",
    },
    twitter: {
      card: "summary_large_image",
      title: config.title,
      description: config.description,
      images: [`${baseUrl}${config.image}`],
      creator: "@kidschedule",
      site: "@kidschedule",
    },
  };
}

/**
 * Generate default (family-focused) metadata
 * 
 * Used when no specific audience is detected.
 */
export function generateDefaultMetadata(): Metadata {
  return generateOGMetadata("family");
}

/**
 * Get OG image URL for a specific audience
 * 
 * @param audience - The target audience segment
 * @returns Full URL to the OG image
 * 
 * @example
 * const imageUrl = getOGImageUrl("coparent");
 * // Returns: "https://kidschedule.com/og/coparent.png"
 */
export function getOGImageUrl(audience: Audience): string {
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || "https://kidschedule.com";
  return `${baseUrl}${OG_IMAGES[audience].image}`;
}

/**
 * Get all audience configurations
 * 
 * Useful for pre-generating OG images or testing.
 */
export function getAllOGConfigs(): Record<Audience, OGImageConfig> {
  return OG_IMAGES;
}
